#ifndef VERSION_H
#define VERSION_H

#define ROBOT_CONTROL_VERSION_MAJOR 1
#define ROBOT_CONTROL_VERSION_MINOR 0
#define ROBOT_CONTROL_VERSION_PATCH 0
#define ROBOT_CONTROL_VERSION "1.0.0"

#endif // VERSION_H